#!/usr/bin/env python3
"""mayhem/oracle/make-observe.py -- regenerate mayhem/oracle/observe.cpp from upstream's suite.

Run by hand when re-pinning (never by build.sh or test.sh; the image needs no Python):
    git show 613d6a1:hevcparser/tests/Parsing.cpp > /tmp/Parsing.cpp
    python3 mayhem/oracle/make-observe.py /tmp/Parsing.cpp --check-expected mayhem/oracle/expected.txt \
        > mayhem/oracle/observe.cpp
then update the SHA-256 list in mayhem/test.sh.

observe.cpp is upstream's hevcparser/tests/Parsing.cpp with the EXPECTED half of every assertion
removed, so the known-answer runners built from it hold no answers (#1787):
  BOOST_CHECK_EQUAL(obs, expected)                 -> KAT_OBS(obs)
  BOOST_CHECK_EQUAL_COLLECTIONS(eb, ee, ob, oe)    -> KAT_OBS_RANGE(ob, oe)  (the parser-side pair)
  BOOST_AUTO_TEST_CASE(X)                          -> KAT_CASE(X)
  the local arrays that only held expected values  -> removed
  the Boost include / suite lines                  -> #include "kat.h" / blank
Every line keeps its number (a multi-line assertion becomes blank lines plus one line ending where
the assertion ended), so the <line> fields of expected.txt still point into upstream's file.
The answers live only in mayhem/oracle/expected.txt, which test.sh reads; with --check-expected
this script also checks every literal expected value in upstream's file against expected.txt.
"""
import hashlib, re, sys

UPSTREAM_SHA256 = "b37cfed89d3b0b7c3c3e57818550a9fd6d9c168fb8388fbfc201fda6d93939b1"  # 613d6a1


def split_args(s, i):
    """s[i] is just after '(' : return (top-level args, index of the matching ')')."""
    depth, start, out, j = 1, i, [], i
    while True:
        c = s[j]
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                out.append(s[start:j])
                return out, j
        elif c == "," and depth == 1:
            out.append(s[start:j])
            start = j + 1
        j += 1


def parser_side(expr):
    return "->" in expr or "consumer" in expr


def main():
    src = open(sys.argv[1]).read()
    if hashlib.sha256(src.encode()).hexdigest() != UPSTREAM_SHA256:
        sys.exit("input is not upstream 613d6a1 hevcparser/tests/Parsing.cpp")
    out, pos, checks, expected_names = [], 0, [], set()
    for m in re.finditer(r"BOOST_CHECK_EQUAL(_COLLECTIONS)?\(", src):
        if m.start() < pos:
            continue
        args, close = split_args(src, m.end())
        args = [a.strip() for a in args]
        end = close + 1
        line = src.count("\n", 0, close) + 1
        if m.group(1):
            assert len(args) == 4, args
            if parser_side(args[2]) and parser_side(args[3]) and not parser_side(args[0]):
                obs, exp = args[2:], args[:2]
            elif parser_side(args[0]) and parser_side(args[1]) and not parser_side(args[2]):
                obs, exp = args[:2], args[2:]
            else:
                sys.exit("cannot tell the sides of line %d: %r" % (line, args))
            new = "KAT_OBS_RANGE(%s, %s)" % tuple(obs)
            expected_names.add(re.match(r"\w+", exp[0]).group(0))
        else:
            assert len(args) == 2, args
            if not parser_side(args[0]) or parser_side(args[1]):
                sys.exit("cannot tell the sides of line %d: %r" % (line, args))
            new = "KAT_OBS(%s)" % args[0]
            exp = [args[1]]
        checks.append((line, exp, m.start()))
        before = src[pos:m.start()]
        nl = src.count("\n", m.start(), end)
        if nl:  # keep the call on the line where the assertion ended, at the same indentation
            indent = before[len(before.rstrip(" \t")):]
            before = before[:len(before) - len(indent)]
            new = "\n" * nl + indent + new
        out.append(before)
        out.append(new)
        pos = end
    out.append(src[pos:])
    body = "".join(out)

    # Remove the local arrays that held only expected values.
    def drop_decl(mo):
        return "" if mo.group(1) in expected_names else mo.group(0)
    body = re.sub(r"[ \t]*uint8_t[ \t]+(\w+)\[\w*\][ \t]*=[ \t]*\{[^}]*\};", drop_decl, body)
    for name in expected_names:
        if re.search(r"(?<!->)(?<!\.)\b%s\b" % name, body):  # not as a member
            sys.exit("expected-only array %s still referenced" % name)

    body = body.replace("#include <boost/test/unit_test.hpp>\n\n",
                        '#include "kat.h"  // mayhem/oracle/kat.h, not Boost\n'
                        "// GENERATED by mayhem/oracle/make-observe.py -- do not edit. Upstream's suite with the\n", 1)
    body = body.replace("BOOST_AUTO_TEST_SUITE(parsing);",
                        "// expected half of every assertion removed: the answers are only in expected.txt.", 1)
    body = body.replace("BOOST_AUTO_TEST_SUITE_END();", "", 1)
    body = re.sub(r"BOOST_AUTO_TEST_CASE\((\w+)\)", r"KAT_CASE(\1)", body)
    if "BOOST_" in body or src.count("\n") != body.count("\n"):
        sys.exit("conversion incomplete")
    sys.stdout.write(body)

    if len(sys.argv) > 2 and sys.argv[2] == "--check-expected":
        # Literal expected values in upstream's file vs expected.txt (same order as the run).
        exp_lines = [l.split() for l in open(sys.argv[3]) if l.startswith("T ")]
        assert len(exp_lines) == len(checks) == 1777, (len(exp_lines), len(checks))
        decls = [(d.start(), d.group(1), d.group(2)) for d in
                 re.finditer(r"uint8_t[ \t]+(\w+)\[\w*\][ \t]*=[ \t]*\{([^}]*)\};", src)]
        lits = mism = 0
        for (line, exp, at), rec in zip(sorted(checks), sorted(exp_lines, key=lambda r: int(r[3]))):
            assert int(rec[3]) == line, (line, rec)
            if len(exp) == 1 and re.fullmatch(r"-?(0x[0-9a-fA-F]+|\d+)", exp[0]):
                want = str(int(exp[0], 0))
            elif len(exp) == 2 and any(nm == exp[0] and d < at for d, nm, _ in decls):
                init = [v for d, nm, v in decls if nm == exp[0] and d < at][-1]  # nearest declaration
                vals = [str(int(v, 0)) for v in init.replace(" ", "").split(",") if v]
                k = re.fullmatch(r"\w+\s*\+\s*(\d+)", exp[1])
                n = int(k.group(1)) if k else len(vals)  # "name + N", or "name + sizeof(name)/..."
                vals += ["0"] * (n - len(vals))
                want = "%d:%s" % (n, ",".join(vals))
            else:
                continue
            lits += 1
            if rec[4] != want:
                mism += 1
                print("MISMATCH line %d: expected.txt %s, upstream literal %s" % (line, rec[4], want), file=sys.stderr)
        print("checked %d literal expected values against expected.txt: %d mismatches" % (lits, mism), file=sys.stderr)
        sys.exit(1 if mism else 0)


main()
