#!/usr/bin/env bash
#
# mayhem/test.sh — check the parser against upstream's OWN functional suite (hevcparser_test:
# hevcparser/tests/Parsing.cpp, 15 Boost test cases of 1777 known-answer assertions on syntax
# elements decoded from real HEVC streams) and decide every verdict here, in this script.
#
# Earlier versions ran upstream's Boost binary and scored the JUnit file it wrote. Any code linked
# into that binary (the parser sources a patch may edit, or the tree's test sources) could write a
# passing report and _exit(0), and an aborted run still counted as 14/15 (#1787, #878). Now:
#
#  1. Pinned suite, without its answers. mayhem/build.sh compiles mayhem/oracle/observe.cpp, never
#     the tree's hevcparser/tests/ (a patch can edit those, #1460). observe.cpp is upstream's
#     Parsing.cpp with the EXPECTED half of every assertion removed (generated by
#     mayhem/oracle/make-observe.py; same line numbers): each BOOST_CHECK_EQUAL(x, want) became
#     KAT_OBS(x), each BOOST_CHECK_EQUAL_COLLECTIONS kept only its parser-side range, and the local
#     arrays of expected values are gone. Each observation prints one record with the value of x,
#       "@@ <nonce> <case> <seq> <line> <value>"
#     and the runner prints "@@ <nonce> <case> END" after the case returns. No program built from the
#     tree contains an answer, and nothing a runner prints, writes or returns means "passed". So a
#     patch that redefines the macros from a tree header ("Hevc.h" is included after kat.h; an
#     earlier version compiled the expected half in, and a header that turned every check into
#     check(b, b) passed with the parser gutted) has no right value to print.
#  2. Verdicts come from this script. The answers are in mayhem/oracle/expected.txt, which is
#     checked against the SHA-256 list below and read into memory before any runner starts, and is
#     never copied to where a runner runs. A record must appear exactly once and equal its
#     expected.txt line; a missing, repeated or different record fails that assertion. <nonce> is
#     a new random number for each process (it marks the record lines; the program can read it, so
#     it is not what stops forging: a patch has no right answer to put in a record without parsing
#     the stream correctly). The HEVC streams are SHA-checked copies of mayhem/test-samples/,
#     checked again before every run.
#  3. One process per test case and build, so a crash or abort fails only that case.
#  4. Each assertion runs in two builds and must give the right answer in both (#1460):
#       N: build-tests/hevc_kat, the parser built with the project's normal flags (upstream CMake
#          Release: -O3 -DNDEBUG -fPIC);
#       G: build-fuzz/hevc_kat, linked with the GRADED objects (build-fuzz/libhevcparser.a, the
#          same objects as /mayhem/hevcesbrowser-console), so code disabled only in the fuzz build
#          (sanitizer, optimisation or macro checks) fails here;
#       W: for SINTEL_FIRST_30 only, build-fuzz/hevc_kat_twin: the parser compiled with the graded
#          flags plus -fsanitize-recover=undefined (UBSan prints its report and carries on; nothing
#          else differs, no runtime options). That stream reaches a real signed overflow in
#          BitstreamReader::getGolombU (hevcparser/src/BitstreamReader.cpp:149) that stops the
#          graded build before its first assertion.
#     The sanitized runners link mayhem/oracle/lsan_off.cc (SPEC.md §6.2 item 15): the pinned suite
#     never frees its input buffers, so leak detection is off in them only; ASan and UBSan stay on.
#
# Limits: the answers are not secret from whoever writes a patch: upstream's Parsing.cpp is in the
# tree (hevcparser/tests/) and expected.txt is in mayhem/oracle/. A patch that carries these
# streams' answers, or pulls them in from one of those files (at run time, or at compile time, e.g.
# a tree header that #includes Parsing.cpp to rebuild the table), and prints them, is not caught.
# Such a patch has to be written for these 1777 values; what is closed is every way to pass
# WITHOUT the answers (macro hijacks, forged reports or END lines, exit codes, aborts).
#
# Tests: one per assertion (1777). It passes when its N record and its G (or W) record are right
# and both processes exited 0 and printed their END line exactly once (30 processes: 15 N, 14 G,
# 1 W). A process that crashes or exits non-zero fails every assertion of its case, including the
# ones it printed before it stopped.
set -uo pipefail
[ -n "${SOURCE_DATE_EPOCH:-}" ] || unset SOURCE_DATE_EPOCH
cd "$SRC" || exit 1

emit_ctrf() {
  local tool="$1" passed="$2" failed="$3" skipped="${4:-0}" pending="${5:-0}" other="${6:-0}"
  local tests=$(( passed + failed + skipped + pending + other ))
  cat > "${CTRF_REPORT:-$SRC/ctrf-report.json}" <<JSON
{
  "results": {
    "tool": { "name": "$tool" },
    "summary": {
      "tests": $tests,
      "passed": $passed,
      "failed": $failed,
      "pending": $pending,
      "skipped": $skipped,
      "other": $other
    }
  }
}
JSON
  printf 'CTRF {"results":{"tool":{"name":"%s"},"summary":{"tests":%d,"passed":%d,"failed":%d,"pending":%d,"skipped":%d,"other":%d}}}\n' \
    "$tool" "$tests" "$passed" "$failed" "$pending" "$skipped" "$other"
  [ "$failed" -eq 0 ]
}

TOOL=hevcparser-test
N_BIN="$SRC/build-tests/hevc_kat"      # project's normal flags
G_BIN="$SRC/build-fuzz/hevc_kat"       # graded objects
W_BIN="$SRC/build-fuzz/hevc_kat_twin"  # graded flags + -fsanitize-recover=undefined
CASES="SURFING_FIRST_30 SINTEL_FIRST_30 VIDEO_H265 E_11345V_4T2_record_part
TearsOfSteel_720p_h265_part Jellyfish_3_Mbps_1080p_hevc_part ffmpeg_default ffmpeg_cp_tr_cm_2020
f265_default homer_default BQSquare_416x240_60_qp37 TestCase1_LifeOfPie_ReEncoded1080pX265_HDR_part
x265_cll HM1 HM2"
W_CASES="SINTEL_FIRST_30"   # second build is W for these, G for the rest
N_ASSERT=1777
RUNS=30

# SHA-256 of every pinned file (paths under mayhem/). The runners were built from the sources;
# test.sh reads expected.txt and feeds the streams.
PINNED_SHA256='
244f4613c70535ff80cc254903c9cad7e4e884cb45290151c6271d50b3f51335  oracle/Params.h
4898043651ab3ada091dce734f921862a9beb8f1ddfd770a0b44f3ff63434325  oracle/observe.cpp
8237bc5823a3bd7de0e16a982f64d4007c1e3835146d926e24086fcb7327428f  oracle/expected.txt
56ed6c10fb00906188ed26e9522c32ff78bf57c2d3cba0b260e3c41524b545f4  oracle/kat.h
1cd9e611aad2dfb1cd5081f7f99c28d61be9cbeb91ded90196cdaf9a1d9df38b  oracle/kat_main.cpp
1c16a5d8aa936ce3f81b5c80ec23f1af6931da3031e43e9d84ad255a6b0fecc3  oracle/lsan_off.cc'
SAMPLES_SHA256='
bfe7400e5835b6822be05eea843f05b5eb0cde11fc2d9c71c33274d246e0530f  10E_11345V_4T2_record_part.265
0b75f1ff29a4f87017c404b7d0bb1131baea47750569343d51a94178364f990f  BQSquare_416x240_60_qp37.bin
d1ac68c4878539cbc1f5b1e5ae552d880d06c2346934e987f26698c8292c6033  HM1.bin
d910fdaeb623508bea35d7db43903419e38d20f812d903e585e148fc15d413d2  HM2.bin
560acc9ecaa5e52de99b5c2abf90569761040e00ec9d1353ad351fbd86ad2347  Jellyfish-3-Mbps-1080p-hevc_part.hevc
707af6cbb8a5d024cd524bbf325274e4514a6faf3118afc48eb6af4f636cf1dd  Sintel_272p_logo_30.265
3dc79fb4dc08d815d36735ff1127833230518b426dab31eb08074e80c7ba1f8a  TearsOfSteel_720p_h265_part.hevc
32e83be665d830c5075a42285e2b51841024de52b6f707a7c92c9f38d759fd42  TestCase1_LifeOfPie_ReEncoded1080pX265_HDR_part.hevc
fa4f716f8b24e9af06b9fd0d6c3e1c5cc60d9c957956eddad204002883e21214  f265_default.hevc
1cb86d0ae6cc68ae97aa5602294dd77a7f1cb1b6eef88d3f4df266c1b7568b40  ffmpeg_cp_tr_cm_2020.hevc
f9fd3107eab8bf5d2dc6b4064314511f74337a2af7fd483f2a2f263e2897bfdf  ffmpeg_default.hevc
75758f89d15d06d8e37a02988a9f9ad69db5c5e7ca0b9e1b163c1685082a1dfe  homer_default.hevc
fbdb6307968b5783d6d19a4107cd95be316e42f4896fd73c1d609cb9d0e3b6c0  surfing_30.265
c18b1cee856d50538e862859df2dae1e079c1a7d79644589db9be4b01446cabe  video-h265.hevc
0c8ccd0c066efaba9d7d07c3aed34fecd5fe421038952abedc80f331e9dbe6c8  x265_cll.hevc
'

fail_all() {   # fail_all <reason> : nothing could be checked
  echo "FATAL: $1" >&2
  emit_ctrf "$TOOL" 0 "$N_ASSERT"
  exit 1
}

for b in "$N_BIN" "$G_BIN" "$W_BIN"; do
  [ -x "$b" ] || fail_all "$b missing (mayhem/build.sh must build it)"
done

WORK="$(mktemp -d "${TMPDIR:-/tmp}/hevc-test.XXXXXX")" || fail_all "mktemp failed"
trap 'rm -rf "$WORK"' EXIT

check_sums() {   # check_sums <dir> <sha256 list> : every file in the list is in <dir> and matches
  ( cd "$1" && printf '%s\n' "$2" | awk 'NF == 2' | sha256sum --check --strict --quiet - ) >&2
}
list_files() { printf '%s\n' "$1" | awk 'NF == 2 { print $2 }'; }

# Private copies, checked after copying, so the checked bytes are the ones used.
PIN="$WORK/pinned"
mkdir "$PIN"
for f in $(list_files "$PINNED_SHA256"); do
  mkdir -p "$PIN/$(dirname "$f")" && cp "$SRC/mayhem/$f" "$PIN/$f" || fail_all "mayhem/$f missing"
done
check_sums "$PIN" "$PINNED_SHA256" || fail_all "mayhem/oracle/ does not match the SHA-256 list in mayhem/test.sh"
FEED="$WORK/samples"
mkdir "$FEED"
for f in $(list_files "$SAMPLES_SHA256"); do
  cp "$SRC/mayhem/test-samples/$f" "$FEED/$f" || fail_all "mayhem/test-samples/$f missing"
done
check_sums "$FEED" "$SAMPLES_SHA256" || fail_all "mayhem/test-samples/ does not match the SHA-256 list in mayhem/test.sh"

# The answers, read into memory before any runner starts; the copy is removed.
EXPECTED="$(awk '$1 == "T"' "$PIN/oracle/expected.txt")"
rm -rf "$PIN"
n="$(printf '%s\n' "$EXPECTED" | awk 'NF == 5' | wc -l)"
[ "$n" -eq "$N_ASSERT" ] || fail_all "expected.txt has $n assertions, want $N_ASSERT"

nonce() { od -An -N8 -tu8 /dev/urandom | tr -d ' \n'; }

# run_case <tier> <binary> <case> : one process runs one case in a fresh directory whose samples/
# holds the checked streams. Writes $WORK/<tier>.<case>.rec ("<tier> <case> <seq> <line> <value>"
# per record with this run's nonce), .out/.err (all output) and .ok (the run passed).
run_case() {
  local t="$1" bin="$2" c="$3" d="$WORK/run.$1.$3" n rc ends
  n="$(nonce)"; : > "$WORK/$t.$c.rec"
  check_sums "$FEED" "$SAMPLES_SHA256" || { echo ">>> $c ($t): a sample stream changed before the run" >&2; return; }
  mkdir -p "$d/samples" && cp "$FEED"/* "$d/samples/"
  ( cd "$d" && "$bin" "$n" "$d" "$c" ) > "$WORK/$t.$c.out" 2> "$WORK/$t.$c.err" < /dev/null; rc=$?
  rm -rf "$d"
  grep -a "^@@ $n $c [0-9]" "$WORK/$t.$c.out" | awk -v T="$t" '{ $1 = T; $2 = ""; print }' \
    | awk '{ $1 = $1; print }' > "$WORK/$t.$c.rec"
  ends="$(grep -acx "@@ $n $c END" "$WORK/$t.$c.out")"
  if [ "$rc" -eq 0 ] && [ "$ends" -eq 1 ]; then : > "$WORK/$t.$c.ok"
  else
    echo ">>> $c ($t, $bin): exit $rc, $ends END lines" >&2
    grep -a -m2 -E 'runtime error|ERROR: AddressSanitizer|^unknown case' "$WORK/$t.$c.err" >&2
  fi
}

runs=()
for c in $CASES; do
  run_case N "$N_BIN" "$c"; runs+=("N.$c")
  case " $W_CASES " in
    *" $c "*) run_case W "$W_BIN" "$c"; runs+=("W.$c") ;;
    *)        run_case G "$G_BIN" "$c"; runs+=("G.$c") ;;
  esac
done
[ "${#runs[@]}" -eq "$RUNS" ] || fail_all "ran ${#runs[@]} processes, want $RUNS"

# A run that did not exit 0 with exactly one END line fails every assertion of its case.
r_pass=0; r_fail=0
for r in "${runs[@]}"; do
  if [ -e "$WORK/$r.ok" ]; then r_pass=$(( r_pass + 1 )); else r_fail=$(( r_fail + 1 )); echo "${r%%.*} ${r#*.}"; fi
done > "$WORK/failed.runs"

# "T <case> <seq> <line> <value>": the N record and the G (or W) record must each appear once,
# equal "<line> <value>", and come from runs that passed.
recs=()
for r in "${runs[@]}"; do recs+=("$WORK/$r.rec"); done
read -r a_pass a_fail < <(printf '%s\n' "$EXPECTED" | awk -v WC=" $W_CASES " '
  function check(t, c, q,   k) {
    k = t SUBSEP c SUBSEP q
    if (!(k in cnt)) return t ": no record"
    if (cnt[k] > 1) return t ": " cnt[k] " records"
    if (rec[k] != $4 " " $5) return t ": got \"" rec[k] "\", want \"" $4 " " $5 "\""
    if ((t SUBSEP c) in badrun) return t ": the run failed"
    return ""
  }
  FILENAME ~ /\/failed\.runs$/ { badrun[$1 SUBSEP $2] = 1; next }
  FILENAME != "-" {
    k = $1 SUBSEP $2 SUBSEP $3; cnt[k]++
    rec[k] = (NF == 5) ? $4 " " $5 : "malformed: " $0
    next
  }
  NF == 5 && $1 == "T" {
    t2 = index(WC, " " $2 " ") ? "W" : "G"
    why = check("N", $2, $3)
    if (why == "") why = check(t2, $2, $3)
    if (why == "") pass++
    else { fail++; if (shown++ < 40) printf "FAIL %s #%d (Parsing.cpp:%d) %s\n", $2, $3, $4, why > "/dev/stderr" }
  }
  END { print pass + 0, fail + 0 }' "$WORK/failed.runs" "${recs[@]}" -)

echo "assertions: ${a_pass:-0} passed, ${a_fail:-0} failed (of $N_ASSERT); runs: $r_pass passed, $r_fail failed (of $RUNS)"

passed=${a_pass:-0}
failed=$(( N_ASSERT - passed ))
emit_ctrf "$TOOL" "$passed" "$failed"
